definitions:
  service.FailResponse:
    properties:
      code:
        example: -1
        type: integer
      data: {}
      message:
        example: something went wrong
        type: string
    type: object
  service.ListData:
    properties:
      count:
        example: 100
        type: integer
      list: {}
    type: object
  service.SuccessResponse:
    properties:
      code:
        example: 200
        type: integer
      data:
        $ref: '#/definitions/service.ListData'
      message:
        example: success
        type: string
    type: object
info:
  contact: {}
paths:
  /problems/details:
    get:
      parameters:
      - description: 问题唯一id
        in: query
        name: problem_identity
        type: string
      responses:
        "200":
          description: 成功返回问题详情
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 问题详情
      tags:
      - 公共方法
  /problems/lists:
    get:
      parameters:
      - description: 请输入页数，默认为1
        in: query
        name: page
        type: integer
      - description: 请输入每页结果个数，默认为20
        in: query
        name: size
        type: integer
      - description: 模糊搜索关键词
        in: query
        name: keyword
        type: string
      - description: 分类唯一id
        in: query
        name: category_identity
        type: string
      responses:
        "200":
          description: 成功返回列表数据
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 问题列表
      tags:
      - 公共方法
  /submit/lists:
    get:
      parameters:
      - description: 请输入页数，默认为1
        in: query
        name: page
        type: integer
      - description: 请输入每页结果个数，默认为20
        in: query
        name: size
        type: integer
      - description: 问题唯一id
        in: query
        name: problem_identity
        type: string
      - description: 用户唯一id
        in: query
        name: user_identity
        type: string
      - description: 状态
        in: query
        name: status
        type: integer
      responses:
        "200":
          description: 成功返回列表数据
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 问题列表
      tags:
      - 公共方法
  /users/details:
    get:
      parameters:
      - description: 用户唯一id
        in: query
        name: identity
        type: string
      responses:
        "200":
          description: 成功返回列表数据
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 用户详情
      tags:
      - 公共方法
  /users/login:
    post:
      parameters:
      - description: 用户昵称
        in: formData
        name: username
        type: string
      - description: 用户密码
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: 成功返回列表数据
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 用户登录
      tags:
      - 公共方法
swagger: "2.0"
