definitions:
  service.FailResponse:
    properties:
      code:
        example: -1
        type: integer
      message:
        example: something went wrong
        type: string
    type: object
  service.ListData:
    properties:
      count:
        example: 100
        type: integer
      list: {}
    type: object
  service.SuccessResponse:
    properties:
      code:
        example: 200
        type: integer
      data:
        $ref: '#/definitions/service.ListData'
      message:
        example: success
        type: string
    type: object
info:
  contact: {}
paths:
  /admin/categories:
    delete:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: identity
        in: query
        name: identity
        required: true
        type: string
      responses:
        "200":
          description: 成功返回问题详情
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 分类删除
      tags:
      - 管理员私有方法
    get:
      parameters:
      - description: 请输入页数，默认为1
        in: query
        name: page
        type: integer
      - description: 请输入每页结果个数，默认为20
        in: query
        name: size
        type: integer
      - description: 模糊搜索关键词
        in: query
        name: keyword
        type: string
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: 成功返回列表数据
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 分类列表
      tags:
      - 管理员私有方法
    post:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: parent_id
        in: formData
        name: parent_id
        type: string
      responses:
        "200":
          description: 成功返回问题详情
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 分类创建
      tags:
      - 管理员私有方法
    put:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: identity
        in: formData
        name: identity
        required: true
        type: string
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: parent_id
        in: formData
        name: parent_id
        type: string
      responses:
        "200":
          description: 成功返回问题详情
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 分类修改
      tags:
      - 管理员私有方法
  /problems:
    post:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 标题
        in: formData
        name: title
        required: true
        type: string
      - description: 内容
        in: formData
        name: content
        required: true
        type: string
      - description: 最大运行时间(s)
        in: formData
        name: max_runtime
        required: true
        type: string
      - description: 最大运行内存(kb)
        in: formData
        name: max_mem
        required: true
        type: string
      - collectionFormat: multi
        description: 分类ID数组
        in: formData
        items:
          type: integer
        name: category_ids
        type: array
      - collectionFormat: multi
        description: 测试样例数组
        in: formData
        items:
          type: string
        name: test_cases
        required: true
        type: array
      responses:
        "200":
          description: 成功返回问题详情
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 问题创建
      tags:
      - 管理员私有方法
  /problems/detail:
    get:
      parameters:
      - description: 问题唯一id
        in: query
        name: problem_identity
        type: string
      responses:
        "200":
          description: 成功返回问题详情
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 问题详情
      tags:
      - 公共方法
  /problems/list:
    get:
      parameters:
      - description: 请输入页数，默认为1
        in: query
        name: page
        type: integer
      - description: 请输入每页结果个数，默认为20
        in: query
        name: size
        type: integer
      - description: 模糊搜索关键词
        in: query
        name: keyword
        type: string
      - description: 分类唯一id
        in: query
        name: category_identity
        type: string
      responses:
        "200":
          description: 成功返回列表数据
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 问题列表
      tags:
      - 公共方法
  /submit/list:
    get:
      parameters:
      - description: 请输入页数，默认为1
        in: query
        name: page
        type: integer
      - description: 请输入每页结果个数，默认为20
        in: query
        name: size
        type: integer
      - description: 问题唯一id
        in: query
        name: problem_identity
        type: string
      - description: 用户唯一id
        in: query
        name: user_identity
        type: string
      - description: 状态
        in: query
        name: status
        type: integer
      responses:
        "200":
          description: 成功返回列表数据
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 提交列表
      tags:
      - 公共方法
  /users/code:
    post:
      parameters:
      - description: mail
        in: formData
        name: mail
        required: true
        type: string
      responses:
        "200":
          description: 成功返回列表数据
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 验证码发送
      tags:
      - 公共方法
  /users/detail:
    get:
      parameters:
      - description: 用户唯一id
        in: query
        name: identity
        type: string
      responses:
        "200":
          description: 成功返回列表数据
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 用户详情
      tags:
      - 公共方法
  /users/login:
    post:
      parameters:
      - description: 用户昵称
        in: formData
        name: username
        type: string
      - description: 用户密码
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: 成功返回列表数据
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 用户登录
      tags:
      - 公共方法
  /users/rank:
    get:
      parameters:
      - description: 请输入页数，默认为1
        in: query
        name: page
        type: integer
      - description: 请输入每页结果个数，默认为20
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: 成功返回列表数据
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 用户排行榜
      tags:
      - 公共方法
  /users/register:
    post:
      parameters:
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      - description: phone
        in: formData
        name: phone
        type: string
      - description: mail
        in: formData
        name: mail
        required: true
        type: string
      - description: code
        in: formData
        name: code
        required: true
        type: string
      responses:
        "200":
          description: 成功返回列表数据
          schema:
            $ref: '#/definitions/service.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/service.FailResponse'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/service.FailResponse'
        "403":
          description: 权限不足
          schema:
            $ref: '#/definitions/service.FailResponse'
        "404":
          description: 资源不存在
          schema:
            $ref: '#/definitions/service.FailResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/service.FailResponse'
      summary: 用户注册
      tags:
      - 公共方法
swagger: "2.0"
